url: 'http://127.0.0.1:8086'
username: ''
password: ''
database: 'NekoGuard'
measurementPrefix: ''
retentionPolicy: ''

commandActionHistoryCount: 3
recordMonsterKilledWithoutCustomName: false
recordEntitiesNaturalSpawn: 3
