url: 'http://127.0.0.1:8086'
username: ''
password: ''
database: 'NekoGuard'
measurementPrefix: ''
retentionPolicy: ''

commandSpeedLimit: 500
commandActionHistoryCount: 3
recordMonsterKilledWithoutCustomName: false
recordEntitiesNaturalSpawn: false
recordContainerActionByNonPlayer: false
recordExplosionWithoutBlocksDestroying: false
recordBlockFadeAndIceFormed: false
recordGrowth: false
mergeContainerAction: true
